version: '2'
services:
  connect-mocks:
    build: 'mockServices'
    ports:
      - 3001:3001
  rabbitmq-x-delay-mgmt:
    build:
      context: ./
      dockerfile: Dockerfile.rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
